apiVersion: v1
kind: Service
metadata:
  name: &app qiita-advent-calendar-2019
  namespace: &ns qiita
  labels:
    app: *app
spec:
  ports:
  - name: srv
    protocol: TCP
    port: 8080
  - name: app
    protocol: TCP
    port: 8090
  selector:
    app: *app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app qiita-advent-calendar-2019
  namespace: &ns qiita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: *app
  template:
    metadata:
      namespace: *ns
      labels:
        app: *app
    spec:
      containers:
      - name: *app
        image: kentakudo/qiita-advent-calendar-2019:latest
        env:
        - name: SRV_PORT
          value: "8080"
        - name: GRPC_PORT
          value: "8090"
        - name: DB_URL
          value: "postgres://qiita_advent_calendar_2019@cockroachdb-proxy:26257/qiita_advent_calendar_2019_db?sslmode=disable"
        - name: SOURCE_KAFKA_VERSION
          valueFrom:
            configMapKeyRef:
              name: kafka-brokers
              key: internal.kafka.broker.version
        - name: SOURCE_BROKERS
          valueFrom:
            configMapKeyRef:
              name: kafka-brokers
              key: internal.kafka.brokers
        - name: SINK_KAFKA_VERSION
          valueFrom:
            configMapKeyRef:
              name: kafka-brokers
              key: internal.kafka.broker.version
        - name: SINK_BROKERS
          valueFrom:
            configMapKeyRef:
              name: kafka-brokers
              key: internal.kafka.brokers
        - name: ACTION_TOPIC
          value: "qiita.action"
        ports:
        - name: srv
          containerPort: 8080
        - name: app
          containerPort: 8090
