apiVersion: v1
kind: Service
metadata:
  labels:
    app: zetcd
  name: zetcd
  namespace: qiita
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
    targetPort: 2181
  selector:
    app: zetcd
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zetcd
  namespace: qiita
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zetcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zetcd
  name: zetcd
  namespace: qiita
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zetcd
  template:
    metadata:
      labels:
        app: zetcd
      namespace: qiita
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - zetcd
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - name: zetcd
        image: quay.io/coreos/zetcd:v0.0.4
        imagePullPolicy: Always
        command:
        - zetcd
        - --zkaddr
        - 0.0.0.0:2181
        - --endpoints
        - kafka-etcd:2379
        ports:
        - containerPort: 2181
          protocol: TCP
        resources:
          requests:
            memory: 80Mi
          limits:
            memory: 200Mi
---
